### PR TITLE
Add icon option to file tree

### LINKED ISSUE #1: support for images, serialized files,
Great project! 

- A lot of scientific projects also have images as output (or input). I would put those in a grey colour.
- Another important file type is binary or serialized data. For R, that would be `.rds`, for python that's commonly `.pkl`. `.bin` could be another. This could also be under the "data" label.
- Maybe there's something to be said for config files (`.Rproj`, `.toml`, etc.)

In general, would it not be a good idea to have the filetype extension filters depend on something external? I tried scitree out on one of my projects, and for example it did not recognise my `.stan` files as code.

### PR DESCRIPTION
**Pull request by jteijema**
I want to add a flag that adds icons to the file tree. Note that Seedir has a styling option for this, but as the styling options are overwritten in the formatter, it doesn't work for scitree.

Moreover, this implementation doesn't depend on the Emoji package.
 
In this PR
- Add icons
- Add icon flag `-e` for emoticon
- Add support for figures
- Add support for serial data
- Add .bat filetype to code_suffixes
- Adjust output text (directory detection, optional icons)

### CODE REVIEW

**Comment by JTeijema** [comment]
image
 ToDo; import the icons and add it to the output

**Comment by JTeijema** [comment]
```python
SCRIPT_ICON = '\U0001F4C4'  # 📄
README_ICON = '\U0001F4D6'  # 📖
DATA_ICON = '\U0001F4DC'    # 📜
FIGURE_ICON = '\U0001F4CA'  # 📊
FOLDER_ICON = '\U0001F4C1'  # 📁
SERIAL_ICON = '\U0001F4E6'  # 📦
```

**Comment by JTeijema** [comment]
I had an issue passing the style function in the scitree function to the formatter. Credits to ChatGPT for the explanation below.


Here is how you can modify the scitree function to pass the icons argument to the natsort_scitree_style function:

```python
def scitree(
    p=".",
    sort=True,
    sort_key=scisort_keygen(),
    formatter=lambda: natsort_scitree_style(icons=True),  # modified
    gitignore=True,
    first="files",
    exclude_folders=[".git"],
    icons=True,
    **kwargs
):
    sd.seedir(
        str(p),
        sort=sort,
        sort_key=sort_key,
        formatter=formatter,
        first=first,
        mask=gi_mask,
        exclude_folders=exclude_folders,
        **kwargs
    )
```

The lambda function will create a new function that calls natsort_scitree_style with the icons argument set to True, and this new function will be passed to the seedir function as the formatter argument.

Alternatively, you can define a separate function that calls natsort_scitree_style with the icons argument, and pass this function to the seedir function as the formatter argument.

@J535D165 do you prefer a modified version of this solution or a separate function?

**Comment by J535D165** [comment]
Thanks a lot. Great improvement. The open questions are good ones. I will experiment with it. Making a custom function for the emoji might be better. I will study this after merging!

**Pull request merged**
